<?php
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	Description: This file is part of the Q2A Spanish Translation
	Author: Gabriel Zanetti http://github.com/pupi1985

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer_title' => '1 Resposta',
		'a_convert_to_c' => 'Convertir aquesta resposta en un comentari',
		'a_convert_to_c_on' => 'Convertir aquesta resposta en un comentari a:',
		'a_convert_warn' => 'Atenció: Aquesta conversió no es pot revertir.',
		'a_convert_warn_cs' => 'Atenció: Aquesta conversió no es pot revertir i moure també els comentaris de la resposta.',
		'add_answer_button' => 'Afegir resposta',
		'add_comment_button' => 'Afegir comentari',
		'add_q_favorites' => 'Afegir aquesta pregunta als meus favorits',
		'anon_name_label' => 'Nom a mostrar (opcional):',
		'a_notify_email' => 'Notificar-me per email si la meva resposta és seleccionada o comentada:',
		'a_notify_label' => 'Notificar-me per email si la meva resposta és seleccionada o comentada',
		'a_notify_x_label' => 'Notificar-me per email (^) si la meva resposta és seleccionada o comentada',
		'answer_button' => 'Respondre',
		'answer_limit' => 'Massa respostes rebudes - si us plau, intenta-ho  novament en una hora',
		'answer_must_be_approved' => 'El teu compte ha de ser aprovat perquè puguis respondre una pregunta.',
		'answer_must_confirm' => "Si us plau, ^5confirma la teva adreça d'email^6 per respondre a aquesta pregunta.",
		'answer_must_login' => "Si us plau, ^1entra^2 o ^3regístra't^4 per respondre a aquesta pregunta.",
		'answer_q_popup' => 'Respondre a aquesta pregunta',
		'approve_a_popup' => 'Aprovar aquesta resposta',
		'approve_button' => 'Aprovar',
		'approve_c_popup' => 'Aprovar aquest comentari',
		'approve_q_popup' => 'Aprovar aquesta pregunta',
		'ask_button' => 'Fer la pregunta',
		'ask_follow_from_a' => 'La teva pregunta estarà relacionada amb aquesta resposta:',
		'ask_follow_title' => 'Fes una pregunta relacionada',
		'ask_limit' => 'Massa preguntes rebudes - si us plau, intenta-ho novament en una hora',
		'ask_must_be_approved' => 'El teu compte ha de ser aprovat perquè puguis fer una pregunta.',
		'ask_must_confirm' => "Si us plau, ^5confirma la teva adreça d'email^6 per fer una pregunta.",
		'ask_must_login' => "Si us plau, ^1entra^2 o ^3regístra't^4 per respondre una pregunta.",
		'ask_same_q' => 'Abans de seguir, si us plau, comprova que la teva pregunta no hagi estat prèviament realitzada:',
		'ask_title' => 'Fes una pregunta',
		'a_waiting_your_approval' => 'Aquesta resposta espera la teva aprovació',
		'a_your_waiting_approval' => 'La teva resposta serà revisada i aprovada aviat.',
		'category_ask_not_allowed' => 'Tu no tens permís per fer preguntes en aquesta categoria',
		'category_js_note' => 'Per seleccionar una categoria, si us plau, habilita Javascript en el teu navegador.',
		'category_required' => 'Si us plau, tria una categoria',
		'claim_button' => 'Jo vaig escriure això',
		'claim_a_popup' => "Assigna aquesta resposta al teu compte d'usuari",
		'claim_c_popup' => "Assigna aquest comentari al teu compte d'usuari",
		'claim_q_popup' => "Assigna aquesta pregunta al teu compte d'usuari",
		'clear_flags_button' => 'Treure marques',
		'clear_flags_popup' => 'Esborrar les marques de tots els usuaris',
		'close_button' => 'Tancar',
		'closed_as_duplicate' => 'tancada com duplicada de:',
		'close_duplicate_error' => "La pregunta duplicada no s'ha pogut trobar - si us plau, torna a entrar el número d'una adreça URL de pregunta diferent, per exemple, 123.",
		'close_duplicate' => "Aquest és un duplicat d'una altra pregunta",
		'closed_with_note' => 'tancada amb la nota:',
		'close_form_button' => 'Tancar pregunta',
		'close_form_title' => 'Tancar aquesta pregunta',
		'close_original_note' => "També pots entrar el número de la pregunta de l'adreça URL, per exemple, 123.",
		'close_original_title' => 'Adreça URL de la pregunta original:',
		'close_q_popup' => 'Tancar aquesta pregunta a noves respostes',
		'close_reason_title' => 'Raó per tancar aquesta pregunta:',
		'c_notify_email' => "Notificar-me per email a aquesta adreça si un comentari s'ha afegit després del meu:",
		'c_notify_label' => "Notificar-me per email si un comentari s'ha afegit després del meu",
		'c_notify_x_label' => "Notificar-me per email (^) si un comentari s'ha afegit després del meu",
		'comment_a_popup' => 'Afegir un comentari en aquesta resposta',
		'comment_button' => 'Comentar',
		'comment_limit' => 'Massa comentaris rebuts - si us plau, intenta-ho novament en una hora',
		'comment_must_be_approved' => 'El teu compte ha de ser aprovat perquè puguis afegir comentaris.',
		'comment_must_confirm' => "Si us plau, ^5confirma la teva adreça d'email^6 per afegir un comentari.",
		'comment_must_login' => "Si us plau, ^1entra^2 o ^3regístra't^4 per afegir un comentari.",
		'comment_on_a' => 'En la resposta: ',
		'comment_on_q' => 'En la pregunta: ',
		'comment_q_popup' => 'Afegir un comentari a aquesta pregunta',
		'c_waiting_your_approval' => 'Aquest comentari espera la teva aprovació',
		'c_your_waiting_approval' => 'El teu comentari serà revisat i aprovat aviat.',
		'delete_a_popup' => 'Esborrar aquesta resposta de forma permanent',
		'delete_button' => 'Esborrar',
		'delete_c_popup' => 'Esborrar aquest comentari de forma permanent',
		'delete_q_popup' => 'Esborrar aquesta pregunta de forma permanent',
		'duplicate_content' => 'La teva entrada sembla que està duplicada.',
		'edit_a_popup' => 'Editar aquesta resposta',
		'edit_a_title' => 'Editar resposta',
		'edit_button' => 'Editar',
		'edit_c_popup' => 'Editar aquest comentari',
		'edit_c_title' => 'Editar comentari',
		'edit_must_confirm' => "Si us plau, ^5confirma la teva adreça d'email^6 per editar-lo.",
		'edit_must_login' => "Si us plau, ^1entra^2 o ^3regístra't^4 per editar-lo.",
		'edit_q_popup' => 'Editar aquesta pregunta',
		'edit_q_title' => 'Editar pregunta',
		'example_tags' => "Etiquetes d'exemple: ",
		'flag_a_popup' => 'Marcar aquesta resposta com spam o inadequada',
		'flag_button' => 'Marcar com inadequat',
		'flag_c_popup' => 'Marcar aquest comentari com spam o inadequat',
		'flag_hide_button' => 'Marcar i ocultar',
		'flag_limit' => 'Massa publicacions marcades - si us plau, intenta-ho novament en una hora',
		'flag_must_confirm' => "Si us plau, ^5confirma la teva adreça d'email^6 per marcar les publicacions.",
		'flag_must_login' => "Si us plau, ^1entra^2 o ^3regístra't^4 per marcar publicacions.",
		'flag_not_allowed' => 'No es permeten marques',
		'flag_q_popup' => 'Marcar aquesta pregunta com spam o inadequada',
		'follow_a_popup' => 'Fer una nova pregunta relacionada amb aquesta resposta',
		'follow_button' => 'Fer pregunta relacionada',
		'follows_a' => 'Relacionada amb una resposta de:',
		'follows_q' => 'Sobre la pregunta:',
		'hide_a_popup' => 'Ocultar aquesta resposta',
		'hide_button' => 'Ocultar',
		'hide_c_popup' => 'Ocultar aquest comentari',
		'hide_q_popup' => 'Ocultar aquesta pregunta',
		'matching_tags' => 'Etiquetes coincidents: ',
		'max_tags_x' => "El nombre màxim d'etiquetes permeses és ^",
		'min_tags_x' => "El nombre mínim d'etiquetes necessàries és ^",
		'notify_email_note' => "Privacitat: La teva adreça d'email només serà utilitzada per enviar-te aquestes notificacions.",
		'q_category_label' => 'Categoria:',
		'q_content_label' => 'Més informació per a la teva pregunta:',
		'q_hidden_author' => 'Aquesta pregunta ha estat ocultada pel seu autor',
		'q_hidden_flagged' => 'Aquesta pregunta ha estat marcada i ocultada',
		'q_hidden_other' => 'Aquesta pregunta ha estat ocultada',
		'q_notify_email' => 'Notificar-me per email si la meva pregunta és resposta o comentada:',
		'q_notify_label' => 'Notificar-me per email si la meva pregunta és resposta o comentada',
		'q_notify_x_label' => 'Notificar-me per email (^) si la meva pregunta és resposta o comentada',
		'q_tags_comma_label' => 'Etiquetes - utilitza coma (,) com separador:',
		'q_tags_label' => 'Etiquetes - utilitza guió mitjà per combinar paraules:',
		'q_title_label' => 'La teva pregunta en una frase:',
		'q_waiting_approval' => 'Aquesta pregunta espera aprovació',
		'q_waiting_your_approval' => 'Aquesta pregunta espera la teva aprovació',
		'q_your_waiting_approval' => 'La teva pregunta serà revisada i aprovada aviat.',
		'recat_button' => 'Recategoritzar',
		'recat_popup' => "Canviar la categoria d'aquesta pregunta",
		'recat_q_title' => 'Recategoritzar pregunta',
		'reject_a_popup' => 'Rebutjar aquesta resposta',
		'reject_button' => 'Rebutjar',
		'reject_c_popup' => 'Rebutjar aquest comentari',
		'reject_q_popup' => 'Rebutjar aquesta pregunta',
		'remove_q_favorites' => 'Treure aquesta pregunta dels meus favorits',
		'reopen_button' => 'Reobrir',
		'reopen_q_popup' => 'Reobrir aquesta pregunta',
		'reply_button' => 'Respondre',
		'reply_c_popup' => 'Respondre a aquest comentari',
		'reshow_a_popup' => 'Tornar a mostrar aquesta resposta',
		'reshow_button' => 'Tornar a mostrar',
		'reshow_c_popup' => 'Tornar a mostrar aquest comentari',
		'reshow_q_popup' => 'Tornar a mostrar aquesta pregunta',
		'retag_button' => 'Reetiquetar',
		'retag_cat_popup' => "Canviar la categoría o etiquetes d'aquesta pregunta",
		'retag_popup' => "Canviar les etiquetes d'aquesta pregunta",
		'retag_q_title' => 'Reetiquetar pregunta',
		'save_silent_label' => 'Guardar de manera silenciosa perquè no es mostri que es van fer edicions',
		'select_popup' => 'Fes clic aquí per triar-la com la millor resposta',
		'select_text' => 'Millor resposta',
		'show_1_comment' => 'Mostrar 1 comentari',
		'show_1_previous_comment' => 'Mostrar 1 comentari previ',
		'show_x_comments' => 'Mostrar ^ comentaris',
		'show_x_previous_comments' => 'Mostrar ^ comentaris previs',
		'unflag_button' => 'Treure marca',
		'unflag_popup' => 'Treure la marca que vas afegir',
		'unselect_popup' => 'Fes clic aquí per eliminar la selecció',
		'x_answers_title' => '^ Respostes',
		'your_answer_title' => 'La teva resposta',
		'your_comment_a' => 'El teu comentari en aquesta resposta:',
		'your_comment_q' => 'El teu comentari en aquesta pregunta:',
	);
