<?php
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	Description: This file is part of the Q2A Spanish Translation
	Author: Gabriel Zanetti http://github.com/pupi1985

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer_title' => '1 Opinió',
		'a_convert_to_c' => 'Convertir aquesta opinió en un comentari',
		'a_convert_to_c_on' => 'Convertir aquesta opinió en un comentari a:',
		'a_convert_warn' => 'Atenció: Aquesta conversió no es pot revertir.',
		'a_convert_warn_cs' => "Atenció: Aquesta conversió no es pot revertir i moure també els comentaris de l'opinió.",
		'add_answer_button' => 'Afegir una opinió',
		'add_comment_button' => 'Afegir comentari',
		'add_q_favorites' => 'Afegir aquest debat als meus favorits',
		'anon_name_label' => 'Nom a mostrar (opcional):',
		'a_notify_email' => 'Notificar-me per email si la meva opinió és seleccionada o comentada:',
		'a_notify_label' => 'Notificar-me per email si la meva opinió és seleccionada o comentada',
		'a_notify_x_label' => 'Notificar-me per email (^) si la meva opinió és seleccionada o comentada',
		'answer_button' => 'Opinar',
		'answer_limit' => 'Masses opinions rebudes - si us plau, intenta-ho  novament en una hora',
		'answer_must_be_approved' => 'El teu compte ha de ser aprovat perquè puguis opinar en un debat.',
		'answer_must_confirm' => "Si us plau, ^5confirma la teva adreça d'email^6 per opinar en aquest debat.",
		'answer_must_login' => "Si us plau, ^1entra^2 o ^3regístra't^4 per opinar en aquest debat.",
		'answer_q_popup' => 'Opinar en aquest debat',
		'approve_a_popup' => 'Aprovar aquesta opinió',
		'approve_button' => 'Aprovar',
		'approve_c_popup' => 'Aprovar aquest comentari',
		'approve_q_popup' => 'Aprovar aquest debat',
		'ask_button' => 'Debatre',
		'ask_follow_from_a' => 'El teu debat estarà relacionat amb aquesta opinió:',
		'ask_follow_title' => 'Proposa un debat relacionat',
		'ask_limit' => 'Massa debats proposats - si us plau, intenta-ho novament en una hora',
		'ask_must_be_approved' => 'El teu compte ha de ser aprovat perquè puguis proposar un debat.',
		'ask_must_confirm' => "Si us plau, ^5confirma la teva adreça d'email^6 per proposar un debat.",
		'ask_must_login' => "Si us plau, ^1entra^2 o ^3regístra't^4 per opinar en un debat.",
		'ask_same_q' => "Abans de seguir, si us plau, comprova que el debat que proposes no s'hagi realitzat anteriorment:",
		'ask_title' => 'Proposa un debat',
		'a_waiting_your_approval' => 'Aquesta opinió espera la teva aprovació',
		'a_your_waiting_approval' => 'La teva opinió serà revisada i aprovada aviat.',
		'category_ask_not_allowed' => 'Tu no tens permís per proposar debats en aquesta categoria',
		'category_js_note' => 'Per seleccionar una categoria, si us plau, habilita Javascript en el teu navegador.',
		'category_required' => 'Si us plau, tria una categoria',
		'claim_button' => 'Jo vaig escriure això',
		'claim_a_popup' => "Assigna aquesta opinió al teu compte d'usuari",
		'claim_c_popup' => "Assigna aquest comentari al teu compte d'usuari",
		'claim_q_popup' => "Assigna aquest debat al teu compte d'usuari",
		'clear_flags_button' => 'Treure marques',
		'clear_flags_popup' => 'Esborrar les marques de tots els usuaris',
		'close_button' => 'Tancar',
		'closed_as_duplicate' => 'tancada com duplicada de:',
		'close_duplicate_error' => "El debat duplicat no s'ha pogut trobar - si us plau, torna a entrar el número d'una adreça URL d'un debat diferent, per exemple, 123.",
		'close_duplicate' => "Aquest és un duplicat d'un altra debat",
		'closed_with_note' => 'tancada amb la nota:',
		'close_form_button' => 'Tancar debat',
		'close_form_title' => 'Tancar aquest debat',
		'close_original_note' => "També pots entrar el número d'un debat de l'adreça URL, per exemple, 123.",
		'close_original_title' => 'Adreça URL del debat original:',
		'close_q_popup' => 'Tancar aquest debat a noves opinions',
		'close_reason_title' => 'Raó per tancar aquest debat:',
		'c_notify_email' => "Notificar-me per email a aquesta adreça si un comentari s'ha afegit després del meu:",
		'c_notify_label' => "Notificar-me per email si un comentari s'ha afegit després del meu",
		'c_notify_x_label' => "Notificar-me per email (^) si un comentari s'ha afegit després del meu",
		'comment_a_popup' => 'Afegir un comentari en aquesta opinió',
		'comment_button' => 'Comentar',
		'comment_limit' => 'Massa comentaris rebuts - si us plau, intenta-ho novament en una hora',
		'comment_must_be_approved' => 'El teu compte ha de ser aprovat perquè puguis afegir comentaris.',
		'comment_must_confirm' => "Si us plau, ^5confirma la teva adreça d'email^6 per afegir un comentari.",
		'comment_must_login' => "Si us plau, ^1entra^2 o ^3regístra't^4 per afegir un comentari.",
		'comment_on_a' => "En l'opinió: ",
		'comment_on_q' => 'En el debat: ',
		'comment_q_popup' => 'Afegir un comentari en aquest debat',
		'c_waiting_your_approval' => 'Aquest comentari espera la teva aprovació',
		'c_your_waiting_approval' => 'El teu comentari serà revisat i aprovat aviat.',
		'delete_a_popup' => 'Esborrar aquesta opinió de forma permanent',
		'delete_button' => 'Esborrar',
		'delete_c_popup' => 'Esborrar aquest comentari de forma permanent',
		'delete_q_popup' => 'Esborrar aquest debat de forma permanent',
		'duplicate_content' => 'La teva entrada sembla que està duplicada.',
		'edit_a_popup' => 'Editar aquesta opinió',
		'edit_a_title' => "Editar l'opinió",
		'edit_button' => 'Editar',
		'edit_c_popup' => 'Editar aquest comentari',
		'edit_c_title' => 'Editar comentari',
		'edit_must_confirm' => "Si us plau, ^5confirma la teva adreça d'email^6 per editar-lo.",
		'edit_must_login' => "Si us plau, ^1entra^2 o ^3regístra't^4 per editar-lo.",
		'edit_q_popup' => 'Editar aquest debat',
		'edit_q_title' => 'Editar el debat',
		'example_tags' => "Etiquetes d'exemple: ",
		'flag_a_popup' => 'Marcar aquesta opinió com spam o inadequada',
		'flag_button' => 'Marcar com inadequada',
		'flag_c_popup' => 'Marcar aquest comentari com spam o inadequat',
		'flag_hide_button' => 'Marcar i ocultar',
		'flag_limit' => 'Massa publicacions marcades - si us plau, intenta-ho novament en una hora',
		'flag_must_confirm' => "Si us plau, ^5confirma la teva adreça d'email^6 per marcar les publicacions.",
		'flag_must_login' => "Si us plau, ^1entra^2 o ^3regístra't^4 per marcar publicacions.",
		'flag_not_allowed' => 'No es permeten marques',
		'flag_q_popup' => 'Marcar aquest debat com spam o inadequat',
		'follow_a_popup' => 'Proposar un nou debat relacionat amb aquesta opinió',
		'follow_button' => 'Proposar un debat relacionat',
		'follows_a' => 'Relacionat amb una opinió de:',
		'follows_q' => 'Sobre el debat:',
		'hide_a_popup' => 'Ocultar aquesta opinió',
		'hide_button' => 'Ocultar',
		'hide_c_popup' => 'Ocultar aquest comentari',
		'hide_q_popup' => 'Ocultar aquest debat',
		'matching_tags' => 'Etiquetes coincidents: ',
		'max_tags_x' => "El nombre màxim d'etiquetes permeses és ^",
		'min_tags_x' => "El nombre mínim d'etiquetes necessàries és ^",
		'notify_email_note' => "Privacitat: La teva adreça d'email només serà utilitzada per enviar-te aquestes notificacions.",
		'q_category_label' => 'Categoria:',
		'q_content_label' => 'Més informació pel teu debat:',
		'q_hidden_author' => 'Aquest debat ha estat ocultat pel seu autor',
		'q_hidden_flagged' => 'Aquest debat ha estat marcat i ocultat',
		'q_hidden_other' => 'Aquest debat ha estat ocultat',
		'q_notify_email' => 'Notificar-me per email si hi ha opinions o comentaris en el meu debat:',
		'q_notify_label' => 'Notificar-me per email si hi ha opinions o comentaris en el meu debat',
		'q_notify_x_label' => 'Notificar-me per email (^) si hi ha opinions o comentaris en el meu debat',
		'q_tags_comma_label' => 'Etiquetes - utilitza coma (,) com separador:',
		'q_tags_label' => 'Etiquetes - utilitza guió mitjà per combinar paraules:',
		'q_title_label' => 'La teva proposta de debat en una frase:',
		'q_waiting_approval' => 'Aquesta proposta de debat espera aprovació',
		'q_waiting_your_approval' => 'Aquesta proposta de debat espera la teva aprovació',
		'q_your_waiting_approval' => 'La teva proposta de debat serà revisat aviat.',
		'recat_button' => 'Recategoritzar',
		'recat_popup' => "Canviar la categoria d'aquest debat",
		'recat_q_title' => 'Recategoritzar debat',
		'reject_a_popup' => 'Rebutjar aquesta opinió',
		'reject_button' => 'Rebutjar',
		'reject_c_popup' => 'Rebutjar aquest comentari',
		'reject_q_popup' => 'Rebutjar aquest debat',
		'remove_q_favorites' => 'Treure aquest debat dels meus favorits',
		'reopen_button' => 'Reobrir',
		'reopen_q_popup' => 'Reobrir aquest debat',
		'reply_button' => 'Opinar',
		'reply_c_popup' => 'Opinar sobre aquest comentari',
		'reshow_a_popup' => 'Tornar a mostrar aquesta opinió',
		'reshow_button' => 'Tornar a mostrar',
		'reshow_c_popup' => 'Tornar a mostrar aquest comentari',
		'reshow_q_popup' => 'Tornar a mostrar aquest debat',
		'retag_button' => 'Reetiquetar',
		'retag_cat_popup' => "Canviar la categoría o etiquetes d'aquest debat",
		'retag_popup' => "Canviar les etiquetes d'aquest debat",
		'retag_q_title' => 'Reetiquetar debat',
		'save_silent_label' => 'Guardar de manera silenciosa perquè no es mostri que es van fer edicions',
		'select_popup' => 'Fes clic aquí per triar-la com la millor opinió',
		'select_text' => 'Millor opinió',
		'show_1_comment' => 'Mostrar 1 comentari',
		'show_1_previous_comment' => 'Mostrar 1 comentari previ',
		'show_x_comments' => 'Mostrar ^ comentaris',
		'show_x_previous_comments' => 'Mostrar ^ comentaris previs',
		'unflag_button' => 'Treure marca',
		'unflag_popup' => 'Treure la marca que vas afegir',
		'unselect_popup' => 'Fes clic aquí per eliminar la selecció',
		'x_answers_title' => '^ Opinions',
		'your_answer_title' => 'La teva opinió',
		'your_comment_a' => 'El teu comentari a aquesta opinió:',
		'your_comment_q' => 'El teu comentari sobre aquest debat:',
	);
