<?php
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	Description: This file is part of the Q2A Spanish Translation
	Author: Gabriel Zanetti http://github.com/pupi1985

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer' => '1 opinió',
		'1_comment' => '1 comentari',
		'1_day' => '1 dia',
		'1_disliked' => '1 negatiu',
		'1_flag' => '1 marca',
		'1_hour' => '1 hora',
		'1_liked' => '1 positiu',
		'1_minute' => '1 minut',
		'1_month' => '1 mes',
		'1_point' => '1 punt',
		'1_question' => '1 debat',
		'1_second' => '1 segon',
		'1_tag' => '1 etiqueta',
		'1_user' => '1 usuari',
		'1_view' => '1 visita',
		'1_vote' => '1 vot',
		'1_week' => '1 setmana',
		'1_year' => '1 any',
		'add_category_x_favorites' => 'Afegir categoria ^ als meus favorits',
		'add_favorites' => 'Afegir als meus favorits',
		'add_tag_x_favorites' => 'Afegir etiqueta ^ als meus favorits',
		'all_categories' => 'Totes les categories',
		'anonymous' => 'anònim',
		'answer_edited' => 'opinió editada',
		'answered_qs_in_x' => 'Debats amb més opinions en ^',
		'answered_qs_title' => 'Debats amb més opinions',
		'answered' => 'opinat',
		'answer_reshown' => 'opinió mostrada de nou',
		'answer_selected' => 'opinió seleccionada',
		'asked' => 'proposat',
		'asked_related_q' => 'debat relacionat',
		'by_x' => 'per: ^',
		'cancel_button' => 'Cancel·la',
		'closed' => 'tancat',
		'commented' => 'comentat',
		'comment_edited' => 'comentari editat',
		'comment_moved' => 'comentari mogut',
		'comment_reshown' => 'comentari mostrat de nou',
		'date_day_min_digits' => '1',
		'date_format_other_years' => '^month ^day, ^year',
		'date_format_this_year' => '^month ^day',
		'date_month_10' => 'Oct',
		'date_month_11' => 'Nov',
		'date_month_12' => 'Des',
		'date_month_1' => 'Gen',
		'date_month_2' => 'Feb',
		'date_month_3' => 'Mar',
		'date_month_4' => 'Abr',
		'date_month_5' => 'Mai',
		'date_month_6' => 'Jun',
		'date_month_7' => 'Jul',
		'date_month_8' => 'Ago',
		'date_month_9' => 'Sep',
		'date_year_digits' => '4',
		'edited' => 'editat',
		'email_error' => "S'ha produït un error en intentar enviar l'email.",
		'field_required' => 'Si us plau, introdueix alguna cosa en aquest camp',
		'file_upload_limit_exceeded' => 'La mida del fitxer excedeix el límit del servidor',
		'general_error' => "S'ha produït un error en el servidor - si us plau, torna a intentar-ho.",
		'hidden' => 'ocult',
		'highest_users' => 'Usuaris millor puntuats',
		'hot_qs_in_x' => 'Debats més actius a ^',
		'hot_qs_title' => 'Debats més actius',
		'image_not_read' => 'La imatge podria no ser llegída. Si us plau, pugi una de: ^',
		'image_too_big_x_pc' => 'Aquesta imatge és massa gran. Si us plau, escàlala a ^% i torna a intentar-ho.',
		'in_category_x' => 'a ^',
		'ip_address_x' => 'Adreça IP ^',
		'logged_in_x' => 'Hola ^',
		'max_length_x' => 'La longitud màxima són ^ caràcters',
		'max_upload_size_x' => 'La mida màxima per pujar arxius és ^',
		'me' => 'mi',
		'meta_order' => '^what^who^when^where', // Determina el orde de elementos como: <respondida> <15 horas atrás> <en Problemas> <por mí (500 puntos)>
		'min_length_x' => 'Si us plau, proporciona més informació (al menys ^ caràcters)',
		'moved' => 'mogut',
		'nav_account' => 'El meu compte',
		'nav_activity' => "Tota l'activitat",
		'nav_admin' => 'Admin',
		'nav_ask' => 'Proposar un debat',
		'nav_categories' => 'Categories',
		'nav_feedback' => 'Enviar feedback',
		'nav_home' => 'Inici',
		'nav_hot' => 'Amb més activitat',
		'nav_login' => 'Entrar',
		'nav_logout' => 'Sortir',
		'nav_most_answers' => 'Amb més opinions',
		'nav_most_recent' => 'Més recents',
		'nav_most_views' => 'Amb més visites',
		'nav_most_votes' => 'Amb més vots',
		'nav_no_answer' => 'Sense resposta',
		'nav_no_selected_answer' => 'Sense resposta seleccionada',
		'nav_no_upvoted_answer' => 'Sense resposta amb vots positius',
		'nav_qa' => 'Q&A',
		'nav_qs' => 'Debats actius',
		'nav_register' => 'Registre',
		'nav_tags' => 'Etiquetes',
		'nav_unanswered' => 'Sense opinió',
		'nav_updates' => 'Les meves Actualitzacions',
		'nav_users' => 'Usuaris',
		'no_active_users' => "No s'han trobat usuaris actius",
		'no_answers_found' => "No s'han trobat opinions",
		'no_answers_in_x' => "No s'han trobat opinions a ^",
		'no_categories_found' => "No s'han trobat categories",
		'no_category' => 'No hi ha categories',
		'no_comments_found' => "No s'han trobat comentaris",
		'no_comments_in_x' => "No s'han trobat comentaris a ^",
		'no_questions_found' => "No s'han trobat debats",
		'no_questions_in_x' => "No s'han trobat debats a ^",
		'no_related_qs_title' => "No s'han trobat debats relacionats",
		'no_results_for_x' => "No s'han trobat resultats per ^",
		'no_tags_found' => "No s'han trobat etiquetes",
		'no_una_questions_found' => "No s'han trobat debats sense opinions",
		'no_una_questions_in_x' => 'Sense debats amb cap opinió a ^',
		'no_unselected_qs_found' => 'No hi ha debats sense una opinió seleccionada',
		'no_unupvoteda_qs_found' => 'No hi ha debats sense opinions amb vots positius',
		'page_label' => 'Pàgina:',
		'page_next' => 'Següent',
		'page_not_found' => 'Pàgina no trobada',
		'page_prev' => 'Anterior',
		'popular_tags' => 'Etiquetes més populars',
		'questions_tagged_x' => 'Debats recentment etiquetades com ^',
		'recategorized' => 'recategorizada',
		'recent_activity_in_x' => 'Activitat recent a ^',
		'recent_activity_title' => 'Activitat recent',
		'recent_as_in_x' => 'Debats amb opinions recents a ^',
		'recent_as_title' => 'Debats amb opinions recents',
		'recent_cs_in_x' => 'Comentaris afegits recentment a ^',
		'recent_cs_title' => 'Comentaris afegits recentment',
		'recent_qs_as_in_x' => 'Debats i opinions recents a ^',
		'recent_qs_as_title' => 'Debats i opinions recents',
		'recent_qs_in_x' => 'Debats actius a ^',
		'recent_qs_title' => 'Debats actius',
		'related_qs_title' => 'Debats relacionats',
		'remove_favorites' => 'Treure dels meus favorits',
		'remove_x_favorites' => 'Treure ^ dels meus favorits',
		'reopened' => 'reobert',
		'reshown' => 'mostrat de nou',
		'results_for_x' => 'Cercar resultats per ^',
		'retagged' => 'reetiquetada',
		'save_button' => 'Guardar canvis',
		'search_button' => 'Cercar',
		'search_explanation' => 'Si us plau, escriu un text en el quadre de recerca i intenta-ho de nou.',
		'search_title' => 'Cerca debats',
		'selected' => 'seleccionada',
		'send_button' => 'Enviar',
		'since_x' => 'des de ^',
		'suggest_ask' => 'Participa en la comunitat ^1proposant un debat^2.',
		'suggest_category_qs' => 'Per veure més, prem a tots els ^1debats en aquesta categoria^2.',
		'suggest_qs' => 'Per veure més, prem per la ^1llista completa de debats^2.',
		'to_x' => 'a ^',
		'suggest_qs_tags' => 'Per veure més, prem a ^1llista completa de debats^2 o ^3etiquetes populars^4.',
		'unanswered_qs_in_x' => 'Debats actius sense opinions a ^',
		'unanswered_qs_title' => 'Debats actius sense opinions',
		'unselected_qs_in_x' => 'Debats sense una opinió seleccionada a ^',
		'unselected_qs_title' => 'Debats actius sense una opinió seleccionada',
		'unupvoteda_qs_in_x' => 'Debats sense una opinió amb vots positius a ^',
		'unupvoteda_qs_title' => 'Debats actius sense una opinió amb vots positius',
		'upload_limit' => 'Massa pujades - si us plau, intenta-ho de nou en una hora',
		'viewed_qs_in_x' => 'Debats més visitats a ^',
		'viewed_qs_title' => 'Debats més visitats',
		'view_q_must_be_approved' => 'El teu compte ha de ser aprovat abans de veure pàgines de debats.',
		'view_q_must_confirm' => 'Si us plau, ^5confirma el teu email^6 per veure la pàgina de debats.',
		'view_q_must_login' => "Si us plau, ^1entra^2 o ^3registra't^4 per veure la pàgina de debats.",
		'voted_down_popup' => 'Fes votat negatiu - prem per treure el vot',
		'vote_disabled_approve' => 'El teu compte ha de ser aprovat abans per poder votar',
		'vote_disabled_down_approve' => 'El teu compte ha de ser aprovat per poder votar negativament',
		'vote_disabled_down' => 'Vot negatiu només disponible per alguns usuaris',
		'vote_disabled_hidden_a' => 'No pots votar opinions ocultes',
		'vote_disabled_hidden_q' => 'No pots votar debats ocults',
		'vote_disabled_level' => 'Només poden votar alguns usuaris',
		'vote_disabled_my_a' => 'No pots votar les teves pròpies opinions',
		'vote_disabled_my_q' => 'No pots votar els teus propis debats',
		'vote_disabled_q_page_only' => 'Si us plau, accedeix al debat per votar',
		'vote_down_must_confirm' => 'Si us plau, ^5confirma el teu email^6 per votar negatiu.',
		'vote_down_popup' => 'Fes clic per votar negatiu',
		'voted_qs_in_x' => 'Debats més votats a ^',
		'voted_qs_title' => 'Debats més votats',
		'voted_up_popup' => 'Has votat positiu - prem per treure el vot',
		'vote_limit' => 'Massa vots rebuts - si us plau, intenta-ho de nou en una hora',
		'vote_must_confirm' => 'Si us plau, ^5confirma el teu email^6 per votar.',
		'vote_must_login' => "Si us plau, ^1entra^2 o ^3registra't^4 per votar.",
		'vote_not_allowed' => 'No està permès votar això',
		'vote_up_popup' => 'Fes clic per votar positiu',
		'written' => '',
		'x_ago' => 'fa ^',
		'x_answers' => '^ opinions',
		'x_comments' => '^ comentaris',
		'x_days' => '^ dies',
		'x_disliked' => '^ negatius',
		'x_flags' => '^ marques',
		'x_hours' => '^ hores',
		'x_liked' => '^ positius',
		'x_minutes' => '^ minuts',
		'x_months' => '^ mesos',
		'x_points' => '^ punts',
		'x_questions' => '^ debats',
		'x_seconds' => '^ segons',
		'x_tags' => '^ etiquetes',
		'x_users' => '^ usuaris',
		'x_views' => '^ visites',
		'x_votes' => '^ vots',
		'x_weeks' => '^ setmanes',
		'x_years' => '^ anys',
	);
