<?php
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	Description: This file is part of the Q2A Spanish Translation
	Author: Gabriel Zanetti http://github.com/pupi1985

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer' => '1 resposta',
		'1_comment' => '1 comentari',
		'1_day' => '1 dia',
		'1_disliked' => '1 negatiu',
		'1_flag' => '1 marca',
		'1_hour' => '1 hora',
		'1_liked' => '1 positiu',
		'1_minute' => '1 minut',
		'1_month' => '1 mes',
		'1_point' => '1 punt',
		'1_question' => '1 pregunta',
		'1_second' => '1 segon',
		'1_tag' => '1 etiqueta',
		'1_user' => '1 usuari',
		'1_view' => '1 visita',
		'1_vote' => '1 vot',
		'1_week' => '1 setmana',
		'1_year' => '1 any',
		'add_category_x_favorites' => 'Afegir categoria ^ als meus favorits',
		'add_favorites' => 'Afegir als meus favorits',
		'add_tag_x_favorites' => 'Afegir etiqueta ^ als meus favorits',
		'all_categories' => 'Totes les categories',
		'anonymous' => 'anònim',
		'answer_edited' => 'resposta editada',
		'answered_qs_in_x' => 'Preguntes més respostes en ^',
		'answered_qs_title' => 'Preguntes més contestades',
		'answered' => 'respost',
		'answer_reshown' => 'resposta mostrada de nou',
		'answer_selected' => 'resposta seleccionada',
		'asked' => 'preguntat',
		'asked_related_q' => 'pregunta relacionada',
		'by_x' => 'per ^',
		'cancel_button' => 'Cancel·la',
		'closed' => 'tancada',
		'commented' => 'comentat',
		'comment_edited' => 'comentari editat',
		'comment_moved' => 'comentari mogut',
		'comment_reshown' => 'comentari mostrat de nou',
		'date_day_min_digits' => '1',
		'date_format_other_years' => '^month ^day, ^year',
		'date_format_this_year' => '^month ^day',
		'date_month_10' => 'Oct',
		'date_month_11' => 'Nov',
		'date_month_12' => 'Des',
		'date_month_1' => 'Gen',
		'date_month_2' => 'Feb',
		'date_month_3' => 'Mar',
		'date_month_4' => 'Abr',
		'date_month_5' => 'Mai',
		'date_month_6' => 'Jun',
		'date_month_7' => 'Jul',
		'date_month_8' => 'Ago',
		'date_month_9' => 'Sep',
		'date_year_digits' => '4',
		'edited' => 'editat',
		'email_error' => 'S'ha produït un error en intentar enviar l'email.',
		'field_required' => 'Si us plau, introdueix alguna cosa en aquest camp',
		'file_upload_limit_exceeded' => 'La mida del fitxer excedeix el límit del servidor',
		'general_error' => 'S'ha produït un error en el servidor - si us plau, torna a intentar-ho.',
		'hidden' => 'ocult',
		'highest_users' => 'Usuaris millor puntuats',
		'hot_qs_in_x' => 'Preguntes més actives a ^',
		'hot_qs_title' => 'Preguntes més actives',
		'image_not_read' => 'La imatge podria no ser llegída. Si us plau, pugi una de: ^',
		'image_too_big_x_pc' => 'Aquesta imatge és massa gran. Si us plau, escàlala a ^% i torna a intentar-ho.',
		'in_category_x' => 'a ^',
		'ip_address_x' => 'Direcció IP ^',
		'logged_in_x' => 'Hola ^',
		'max_length_x' => 'La longitud màxima són ^ caracters',
		'max_upload_size_x' => 'La mida màxima per pujar arxius és ^',
		'me' => 'mi',
		'meta_order' => '^what^who^when^where', // Determina el orde de elementos como: <respondida> <15 horas atrás> <en Problemas> <por mí (500 puntos)>
		'min_length_x' => 'Si us plau, proporciona més informació (al menys ^ caràcters)',
		'moved' => 'mogut',
		'nav_account' => 'El meu compte',
		'nav_activity' => 'Tota l'activitat',
		'nav_admin' => 'Admin',
		'nav_ask' => 'Fer una pregunta',
		'nav_categories' => 'Categories',
		'nav_feedback' => 'Enviar feedback',
		'nav_home' => 'Inici',
		'nav_hot' => 'Més actives',
		'nav_login' => 'Ingressar',
		'nav_logout' => 'Sortir',
		'nav_most_answers' => 'Més contestades',
		'nav_most_recent' => 'Recents',
		'nav_most_views' => 'Més visitades',
		'nav_most_votes' => 'Més votades',
		'nav_no_answer' => 'Sense resposta',
		'nav_no_selected_answer' => 'Sense resposta seleccionada',
		'nav_no_upvoted_answer' => 'Sense resposta amb vots positius',
		'nav_qa' => 'Q&A',
		'nav_qs' => 'Preguntes',
		'nav_register' => 'Registre',
		'nav_tags' => 'Etiquetes',
		'nav_unanswered' => 'Sense respondre',
		'nav_updates' => 'Les meves Actualitzacions',
		'nav_users' => 'Usuaris',
		'no_active_users' => 'No s'han trobat usuaris actius',
		'no_answers_found' => 'No s'han trobat respostes',
		'no_answers_in_x' => 'No s'han trobat respostes a ^',
		'no_categories_found' => 'No s'han trobat categories',
		'no_category' => 'No hi ha categories',
		'no_comments_found' => 'No s'han trobat comentaris',
		'no_comments_in_x' => 'No s'han trobat comentaris a ^',
		'no_questions_found' => 'No s'han trobat preguntes',
		'no_questions_in_x' => 'No s'han trobat preguntes a ^',
		'no_related_qs_title' => 'No s'han trobat preguntes relacionades',
		'no_results_for_x' => 'No s'han trobat resultats per ^',
		'no_tags_found' => 'No s'han trobat etiquetes',
		'no_una_questions_found' => 'No s'han trobat preguntes sense contestar',
		'no_una_questions_in_x' => 'Sin preguntas no respondidas en ^',
		'no_unselected_qs_found' => 'No hay preguntas sin una respuesta seleccionada',
		'no_unupvoteda_qs_found' => 'No hay preguntas sin respuestas con votos positivos',
		'page_label' => 'Página:',
		'page_next' => 'Siguiente',
		'page_not_found' => 'Página no encontrada',
		'page_prev' => 'Anterior',
		'popular_tags' => 'Etiquetas más populares',
		'questions_tagged_x' => 'Preguntas recientemente etiquetadas como ^',
		'recategorized' => 'recategorizada',
		'recent_activity_in_x' => 'Actividad reciente en ^',
		'recent_activity_title' => 'Actividad reciente',
		'recent_as_in_x' => 'Preguntas respondidas recientemente en ^',
		'recent_as_title' => 'Preguntas respondidas recientemente',
		'recent_cs_in_x' => 'Comentarios añadidos recientemente en ^',
		'recent_cs_title' => 'Comentarios añadidos recientemente',
		'recent_qs_as_in_x' => 'Preguntas y respuestas recientes en ^',
		'recent_qs_as_title' => 'Preguntas y respuestas recientes',
		'recent_qs_in_x' => 'Preguntas recientes en ^',
		'recent_qs_title' => 'Preguntas recientes',
		'related_qs_title' => 'Preguntas relacionadas',
		'remove_favorites' => 'Remover de mis favoritos',
		'remove_x_favorites' => 'Remover ^ de mis favoritos',
		'reopened' => 'reabierta',
		'reshown' => 'mostrada de nuevo',
		'results_for_x' => 'Buscar resultados para ^',
		'retagged' => 'reetiquetada',
		'save_button' => 'Guardar cambios',
		'search_button' => 'Buscar',
		'search_explanation' => 'Por favor, ingresa texto en el cuadro de búsqueda e inténtalo nuevamente.',
		'search_title' => 'Buscar preguntas',
		'selected' => 'seleccionada',
		'send_button' => 'Enviar',
		'since_x' => 'desde ^',
		'suggest_ask' => 'Participa en la comunidad ^1haciendo una pregunta^2.',
		'suggest_category_qs' => 'Para ver más, presiona en todas las ^1preguntas en esta categoría^2.',
		'suggest_qs' => 'Para ver más, presiona para la ^1lista completa de preguntas^2.',
		'to_x' => 'a ^',
		'suggest_qs_tags' => 'Para ver más, presiona en ^1lista completa de preguntas^2 o ^3etiquetas populares^4.',
		'unanswered_qs_in_x' => 'Preguntas recientes sin respuesta en ^',
		'unanswered_qs_title' => 'Preguntas recientes sin respuesta',
		'unselected_qs_in_x' => 'Preguntas sin una respuesta seleccionada en ^',
		'unselected_qs_title' => 'Preguntas recientes sin una respuesta seleccionada',
		'unupvoteda_qs_in_x' => 'Preguntas sin una respuesta con votos positivos en ^',
		'unupvoteda_qs_title' => 'Preguntas recientes sin una respuesta con votos positivos',
		'upload_limit' => 'Demasiadas subidas - por favor, inténtalo de nuevo en una hora',
		'viewed_qs_in_x' => 'Preguntas más vistas en ^',
		'viewed_qs_title' => 'Preguntas más vistas',
		'view_q_must_be_approved' => 'Tu cuenta debe primero ser aprobada para ver páginas de preguntas.',
		'view_q_must_confirm' => 'Por favor, ^5confirma tu dirección de email^6 para ver la página de preguntas.',
		'view_q_must_login' => 'Por favor, ^1ingresa^2 o ^3regístrate^4 para ver la página de preguntas.',
		'voted_down_popup' => 'Haz votado negativo - presiona para quitar el voto',
		'vote_disabled_approve' => 'Tu cuenta debe primero ser aprobada para poder votar',
		'vote_disabled_down_approve' => 'Tu cuenta debe ser aprobada para poder votar negativamente',
		'vote_disabled_down' => 'Voto negativo sólo disponible para algunos usuarios',
		'vote_disabled_hidden_a' => 'No puedes votar respuestas ocultas',
		'vote_disabled_hidden_q' => 'No puedes votar preguntas ocultas',
		'vote_disabled_level' => 'Sólo pueden votar algunos usuarios',
		'vote_disabled_my_a' => 'No puedes votar tus propias respuestas',
		'vote_disabled_my_q' => 'No puedes votar tus propias preguntas',
		'vote_disabled_q_page_only' => 'Por favor, accede a la pregunta para votar',
		'vote_down_must_confirm' => 'Por favor, ^5confirma tu dirección de email^6 para votar negativo.',
		'vote_down_popup' => 'Haz clic para votar negativo',
		'voted_qs_in_x' => 'Preguntas más votadas en ^',
		'voted_qs_title' => 'Preguntas más votadas',
		'voted_up_popup' => 'Has votado positivo - presiona para quitar el voto',
		'vote_limit' => 'Demasiados votos recibidos - por favor, inténtalo de nuevo en una hora',
		'vote_must_confirm' => 'Por favor, ^5confirma tu dirección de email^6 para votar.',
		'vote_must_login' => 'Por favor, ^1ingresa^2 o ^3regístrate^4 para votar.',
		'vote_not_allowed' => 'No está permitido votar esto',
		'vote_up_popup' => 'Haz clic para votar positivo',
		'written' => '',
		'x_ago' => 'hace ^',
		'x_answers' => '^ respuestas',
		'x_comments' => '^ comentarios',
		'x_days' => '^ días',
		'x_disliked' => '^ negativos',
		'x_flags' => '^ marcas',
		'x_hours' => '^ horas',
		'x_liked' => '^ positivos',
		'x_minutes' => '^ minutos',
		'x_months' => '^ meses',
		'x_points' => '^ puntos',
		'x_questions' => '^ preguntas',
		'x_seconds' => '^ segundos',
		'x_tags' => '^ etiquetas',
		'x_users' => '^ usuarios',
		'x_views' => '^ visitas',
		'x_votes' => '^ votos',
		'x_weeks' => '^ semanas',
		'x_years' => '^ años',
	);
